### ISSUE TITLE
Artist Carousel

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#129]
> @stravid87:
> I love art and artist love showing off their art. I wonder if we can also find a way to use light boxes to highlight. This will provide another interesting angle that we can use. (It also is a great way to get people to the site. In fact, holding art competitions might even work better than essay competitions because it is so accessible).

**Comment by arnonrdp** [comment]
@stravid87, I like this idea.

How do you think we can do this?
Do you have a website or maybe a portfolio so we can get a visual idea of the whole thing?

**Comment by stravid87** [comment]
No actually.... Well I have ideas but nothing concrete. Would be a very simple variation on the Prompt / Entry flow.
My plan is to scrutinize the next production version 1.1 for bugs. At that time, I'll also weigh in on a way forward for this idea?

**Comment by arnonrdp** [comment]
Here I was thinking in something similar to [Pinterest](pinterest.com).

**Comment by stravid87** [comment]
On my TODO. I think I'll pull out Figma and do some design sketch once I get to Ottawa next week (visiting my parents at present).

**Comment by arnonrdp** [comment]
Sounds great to me, let's discuss more about it on Saturday.

**Comment by stravid87** [comment]
![Image](https://user-images.githubusercontent.com/116566901/223607666-0413a54c-8bb6-41f4-a3c5-705ab04c1e82.png)

**Comment by stravid87** [comment]
I love art... but it costs to produce and won't bring us much in the immediate. In time, I think it's a very useful add to our app, but not the immediate priority in my opinion. I do love art though and so I think we should definitely have a way to show it off. 

After this carousel, the next stage would be to have art as Entries -- that is, do a competition where instead of essays it's art. However, we should probably just dovetail this into an already working solution and not worry about it being top priority. 

Also, optimization will slowly become a go to for us and this has the risk of causing bloat.

**Comment by arnonrdp** [comment]
I got it, this seems to be a big task, maybe we split it into 2.

It needs to be discussed in a call, imo.

**Comment by stravid87** [comment]
> I got it, this seems to be a big task, maybe we split it into 2.
> 
> It needs to be discussed in a call, imo.

Good idea. Let's keep it low priority regardless.
Right now I really want to focus on getting the writing team autonomy so that they can post their own entries and own prompts.
The sooner we can get them using the site to do tasks, the sooner we can get into a tight feedback loop of iteration.
