### ISSUE TITLE
Add Reading Time to Prompts and Entries

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#27]
Currently this information is hard-coded as "9 min read".

The proposal here is to obtain the amount of words in the description and use it to predict reading time.

To do this, you'll need to do a search on the number of words read per minute (on average, of course).

**Comment by stravid87** [comment]
I like it! Looking forward to digging into this.

**Comment by stravid87** [comment]
I managed this problem by adding a simple function that scrubs the description of  likely HTML and then returns an estimate.

```
function giveReadingTime(description) {
  let stringArr = description.split(' ')
  let adjustment = 0
  stringArr = stringArr.filter((el) => {
    //removes anything that's an html tag
    if (el.indexOf('<') == -1) {
      return el
    } else {
      adjustment++
    }
  })

  let wordCount = stringArr.length + adjustment
  return Math.round(wordCount / 238) //238 words / min accroding to https://psyarxiv.com/xynwg/
}
```

Next I changed the hard coded "9" to the dynamic value `{{ giveReadingTime(prompt.description) }}`

Let's go through the committing process tomorrow? (mostly cause I need to run to clinic now!)

**Comment by arnonrdp** [comment]
This function looks good, but are you removing just HTML characters, like `<`, or HTML elements as well?

**Comment by stravid87** [comment]
I did some research, apparently trying to parse HTML with Regex is not possible. So, to really do it perfectly would require a parsing engine likely more complex than what we need. 
When then string is split on the &nbsp, elements such as "<div>one two three</div>" get parse as ["<div>one", "two"," three</div>"]. By filtering these out, the word count is accidentally lowered and that's why for every entry filtered, 1 is added to the adjustment.
