### ISSUE TITLE
Fix the glitch when clicking on the Subscribe button

### ISSUE THREAD

**Issue by arnonrdp** [globe-and-citizen/Celebrity-Fanalyzer#346]
There is a strange glitch when we click on the Subscribe button: it seems that the number of likes is also momentarily changed

https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/26576201/e1263f56-3e04-4a3b-920d-7e0fea8680df

**Comment by sathudeva7** [comment]
@arnonrdp  When routing to a specific prompt, there appears to be a glitch where the like, dislike, share, and comment counts are not updated immediately. The issue seems to stem from the unmounted part not being properly reset, causing it to display the previous prompt's counts temporarily. Please see the video demo of this bug for reference. https://jam.dev/c/45574a65-33b8-4487-a42d-e6f7cb0defc9 . I fixed that bug also in this commit. Please review the changes. Thanks
