### ISSUE TITLE
[BUG] Prompts with Winners Still Populating the Entry Card

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#454]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marclupanc** [comment]
This bug is only relevant for production, as all the older prompts (before winner selection was implemented) don't have the winner selected in admin panel. 

The easies solution (no code changes/PR needed) is to go through all the prompts and select a winner for each of them (probably could ask Taiba who was the winner for each prompt). This way each prompt will have a winner selected, and creating new entry will be possible only for the prompts with no winner selected (current prompt)

**Development branch:**

![Image](https://github.com/user-attachments/assets/3957a7e3-e29c-4ec7-96b9-a6f3d0009562)

![Image](https://github.com/user-attachments/assets/6f77f617-711b-4ef7-9403-2f08a00c9be8)


**Production:**

![Image](https://github.com/user-attachments/assets/ccb2ef74-9e67-4fb6-9377-a853629a9580)



![Image](https://github.com/user-attachments/assets/88354bb6-4a3f-4d05-b20d-3fda60d4f387)

**Comment by marclupanc** [comment]
Fixed with latest release. Entry creation only available for a prompt that has an escrowId.
