### ISSUE TITLE
Possibility to change the Author of a Prompt/Entry

### ISSUE THREAD

**Issue by stravid87** [globe-and-citizen/Celebrity-Fanalyzer#89]
When creating entries, there is no way to attribute credit to a different third party.

So, for example, I'm posting a December entry on behalf of another writer and I can't credit. Or at least, My photo is always there beside the prompts and entries that I create.

**Comment by arnonrdp** [comment]
Here we need to define some points:
- Does the real author need to be registered in the application?
- Can you imagine a link directing to his profile?
   - If so, we need to think about user profiles in general;
   - If not, just reference his name? We could put a link to some social network.

I like the idea of the user being registered in the application, in terms of the database it's good to reference him.

**Comment by stravid87** [comment]
Very good points. 

- In the beginning, no, the real author does not __need__ to be registered -- we as admins will be doing the input and likely primarily me as their point of contact. However, we can request / require this if we want (I'm paying them money after all to participate so we could likely it a requirement.) These users, you can tag with the role, "author", instead of "admin".
- I think this would be an excellent addition as soon as we have writers actively requesting a "Celebrity Fanalyzer" profile. More likely, that won't happen until Celebrity Fanalyzer => Globe & Citizen. More likely, we should just include a way to include their links to their other social platform handles as you suggest.

**Comment by arnonrdp** [comment]
Great, we can think about starting to work with roles from right now.

**Comment by arnonrdp** [comment]
I've been thinking of different ways to make this work in a way that's simple and straightforward.

I came to the conclusion that the simplest thing is that instead of adding a writer to a prompt/entry, we just need to be able to edit the user who created it.

To explain: if I add a field for specifying the writer, we can have the redundancy of having a creator user and a writer for a given prompt/entry.
I realized that it would be much simpler to be able to edit the user who created it, something like a list of users in a dropdown.

---

To make it work in the best way, we need the user to log in to our application.
Thus, we will have the writer's reference to be able to display it in the list of writers.

----

But when I start talking about writers, I'm referring to a role, so it would be best to take a step back and work with roles first.

**Comment by arnonrdp** [comment]
Now that users have roles, I'm coming back to this issue.

**Comment by stravid87** [comment]
> Now that users have roles, I'm coming back to this issue.

Sounds good. What are the roles you're currently thinking of? I've been waffling on the best way to start engaging writers. In the beginning requiring a Gmail account is reasonable. In the beginning / previously, I was thinking to keep it very transient the relationships. Now though, I actually am changing my mind and leaning towards a stable 3 - 5 participants -- I'll explain more on our call tomorrow.
